source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

target :Pola do
    use_modular_headers!
    pod 'AFNetworking', '2.3.1'
    pod 'Objection', '1.4'
    pod 'UITextView+Placeholder'
    pod 'KVNProgress'
    
    target :PolaTests do
      use_frameworks!
      pod 'iOSSnapshotTestCase'
    end
    
    target :PolaUITests do
      use_frameworks!
      pod 'iOSSnapshotTestCase'
      pod 'Swifter', '~> 1.4.7'
    end

end
